### ISSUE TITLE
Next Aired 

### ISSUE THREAD

**Issue by Blurayx** [marcelveldt/script.skin.helper.service#100]
Hi marcelveldt.
The old Next Aired use to automatically exit when changes were made when ok was clicked, would it be possible to add this feature back?

Thanks

**Comment by marcelveldt** [comment]
Can you explain to me what you mean because I have no idea.

**Comment by Blurayx** [comment]
Basically, next Aired would close to make sure the new settings take effect when the ok button was clicked 
https://imgur.com/zbxGaF5
