### ISSUE TITLE
In progress widget goes to tv show view not episode view

### ISSUE THREAD

**Issue by BinsonBuzz** [marcelveldt/script.skin.helper.service#101]
I've just started using Estuary Mod V2 on Kodi V18.  I spotted that when you create a custom 'in progress tv shows' widget, rather than taking you to the latest unwatched episode as per the kodi settings, it takes you to the tv show page

https://forum.kodi.tv/showthread.php?tid=306757&pid=2643975#pid2643975

**Comment by marcelveldt** [comment]
The widget is "In progress TV Shows" so it will indeed take you to the tvshow listing itself.
If you need a behaviour where you just see the latest unwatched episode, you should use the next episodes widget instead.
