### ISSUE TITLE
next aired

### ISSUE THREAD

**Issue by ghost** [marcelveldt/script.skin.helper.service#107]
@marcelveldt im running the latest next aired build 7.0.1 my tv shows are displaying the wrong show for the day.  The blacklist s05e01 aires tomorrow in the U.S 27th but im from australia and its already the 27th so its showing up already is there a way to change this it use to be ok but must have changed. I just checked 6.0.15 and days are correct but no posters or banners display

**Comment by marcelveldt** [comment]
I'm still figuring out a way to do this properly as the api is lacking timezone information.

**Comment by ghost** [comment]
ok cool good to hear wasnt sure if you knew about it thanks for getting back to me love the work your doing

**Comment by Angelinas1** [comment]
Fixed....add timezone in tvdb module.
