### ISSUE TITLE
setkodisetting function broken

### ISSUE THREAD

**Issue by sualfred** [marcelveldt/script.skin.helper.service#108]
Hey Marcel,

This function seems to be broken.

In my case I'm calling it with:
`<onclick>RunScript(script.skin.helper.service,action=setkodisetting,setting=videolibrary.tvshowsselectfirstunwatcheditem,value=2)</onclick>`

But nothing is going to be changed and the log throws an error

> 13:35:53.934 T:1344   DEBUG: Skin Helper Service --> MainModule called with parameters: {'action': 'setkodisetting', 'setting': 'videolibrary.tvshowsselectfirstunwatcheditem', 'value': '2'}
13:35:53.934 T:1344   DEBUG: Skin Helper Service --> {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
13:35:53.934 T:1344   DEBUG: Skin Helper Service --> {'params': {'setting': 'videolibrary.tvshowsselectfirstunwatcheditem', 'value': '"2"'}, 'jsonrpc': '2.0', 'method': 'Settings.SetSettingValue', 'id': 1}

**Comment by marduklev** [comment]
NON JON wrote on 10.06.2018, dont know if that helps
Found the problem. The function setkodisetting() in main_module.py: elif  is_int: value = '"%s"' % value Should be: elif  not is_int: value = '"%s"' % value
--

**Comment by Angelinas1** [comment]
fixed...
Add new value (for integer), separate valeue for string and integer.
Example:
    '<onload>RunScript(script.skin.helper.service,action=setkodisetting,setting=lookandfeel.stereostrength,numvalue=2)</onload>'
