### ISSUE TITLE
forced views going crazy :-)  also streams & LibraryMonitor errors

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#11]
Hi Marcel - 
Great work - love all the new features coming out.

just noticed a couple issues in the latest helper .8 and skin 3.5.7

forced views have gone haywire in the latest script and skin update.
sometimes they are correct other times they inherit the previous windows settings or are just wrong.  A couple times I have seen the view correct itself after a 5-10 second delay.

also seems like an error is being throw quite often when viewing streams via 3rd party video add ons like Genesis in this instance...

23:12:27 T:13264   ERROR: Traceback (most recent call last):
23:12:27 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 179, in run
23:12:27 T:13264   ERROR:     self.setStreamDetails()
23:12:27 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 845, in setStreamDetails
23:12:27 T:13264   ERROR:     if json_result: streamdetails = json_result["streamdetails"]
23:12:27 T:13264   ERROR: UnboundLocalError: local variable 'json_result' referenced before assignment
23:12:27 T:13264  NOTICE: Skin Helper Service --> ERROR in LibraryMonitor ! --> local variable 'json_result' referenced before assignment
23:12:27 T:13264   ERROR: Traceback (most recent call last):
23:12:27 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 179, in run
23:12:27 T:13264   ERROR:     self.setStreamDetails()
23:12:27 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 845, in setStreamDetails
23:12:27 T:13264   ERROR:     if json_result: streamdetails = json_result["streamdetails"]
23:12:27 T:13264   ERROR: UnboundLocalError: local variable 'json_result' referenced before assignment
23:12:27 T:9408  NOTICE: Thread FileCache start, auto delete: false
23:12:28 T:13264  NOTICE: Previous line repeats 4 times.
23:12:28 T:13264  NOTICE: Skin Helper Service --> ERROR in LibraryMonitor ! --> local variable 'json_result' referenced before assignment
23:12:28 T:13264   ERROR: Traceback (most recent call last):
23:12:28 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 179, in run
23:12:28 T:13264   ERROR:     self.setStreamDetails()
23:12:28 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 845, in setStreamDetails
23:12:28 T:13264   ERROR:     if json_result: streamdetails = json_result["streamdetails"]
23:12:28 T:13264   ERROR: UnboundLocalError: local variable 'json_result' referenced before assignment
23:12:29 T:2028  NOTICE: Thread FileCache start, auto delete: false
23:12:30 T:13264  NOTICE: Previous line repeats 3 times.
23:12:30 T:13264  NOTICE: Skin Helper Service --> ERROR in LibraryMonitor ! --> local variable 'json_result' referenced before assignment
23:12:30 T:13264   ERROR: Traceback (most recent call last):
23:12:30 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 179, in run
23:12:30 T:13264   ERROR:     self.setStreamDetails()
23:12:30 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 845, in setStreamDetails
23:12:30 T:13264   ERROR:     if json_result: streamdetails = json_result["streamdetails"]
23:12:30 T:13264   ERROR: UnboundLocalError: local variable 'json_result' referenced before assignment
23:12:30 T:4816  NOTICE: Thread FileCache start, auto delete: false
23:12:30 T:13264  NOTICE: Skin Helper Service --> ERROR in LibraryMonitor ! --> local variable 'json_result' referenced before assignment
23:12:30 T:13264   ERROR: Traceback (most recent call last):
23:12:30 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 179, in run
23:12:30 T:13264   ERROR:     self.setStreamDetails()
23:12:30 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 845, in setStreamDetails
23:12:30 T:13264   ERROR:     if json_result: streamdetails = json_result["streamdetails"]
23:12:30 T:13264   ERROR: UnboundLocalError: local variable 'json_result' referenced before assignment
23:12:31 T:13264  NOTICE: Skin Helper Service --> ERROR in LibraryMonitor ! --> local variable 'json_result' referenced before assignment
23:12:31 T:13264   ERROR: Traceback (most recent call last):
23:12:31 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 179, in run
23:12:31 T:13264   ERROR:     self.setStreamDetails()
23:12:31 T:13264   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\LibraryMonitor.py", line 845, in setStreamDetails
23:12:31 T:13264   ERROR:     if json_result: streamdetails = json_result["streamdetails"]
23:12:31 T:13264   ERROR: UnboundLocalError: local variable 'json_result' referenced before assignment

**Comment by marcelveldt** [comment]
Forced views working fine for me, maybe it's only in error when using an addon ?
Most of those crappy addons like genesis try to set the view themselves too or present the wrong contenttype to Kodi.

Can you please test with both addon and normal library ?

I'll look into that issue with the stream details

**Comment by mgonzales71** [comment]
the errors above from the log I do not think are related to the forced views issue.

i noticed it happens with a tv show like "Cops" (28 seasons) and other library nodes with a lot of items.

i have turned forced views off for now - I can turn it back on and resume testing more later today after i catch up on a few shows - i think that oddness I was seeing was actually crashing Kodi because once I turned off forced views I haven't had a crash - I had about 5 crashes with this update before turning it off.

right now - i am feeling lots of items may be a possible cause - i will resume testing and let you know if I discover anything new.

thanks - mario

**Comment by marcelveldt** [comment]
The errors in your log were caused by the streamdetails function I just fixed that.

The forced views... I can't reproduce the error so I hope you can find anything with testing.

**Comment by marcelveldt** [comment]
Watched some tv shows tonight myself with forced views ON and didn't notice any strange behavior or crash except that when you enter a show for the first time it jumps in a flash to the correct view. Will only do this at first launch and I'm not sure if I can fix that.
