### ISSUE TITLE
webservice (aka http://localhost:52307/getartwork...) seems broken

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#110]
been banging my head on this so wanted to re-ask in a more specific issue post since you may not have noticed the last few replies to the following that mention this issue...

https://github.com/marcelveldt/script.skin.helper.service/issues/99

But it appears a recent update may have broken the web service artwork lookup (relatively speaking that is... but one of the most recent commits to the skin helper service script and related framework) 

specifically getartwork, seems to not work no matter which way I try - the getthumb method for general google image lookup seems to work but is not specific enough results for needs such as a logo, clearart, banner, poster, etc

when you have a change could you please check and verify it works for you -- maybe the wiki is out of date and I am using it wrong?

I thank you in advance greatly and most appreciatively once you do get a chance to look at this!

and as always a HUGE thanks for all your hard work and help Marcel!

can't ever say enough how awesome your hard work is appreciated and how it has improved skinning with Kodi 

👍 

Mario

**Comment by Angelinas1** [comment]
This was limeted by fanart.tv...
I can set to use tmdb, but only poster and fanart.
