### ISSUE TITLE
ListItem.Premiered shows incorrect year field when called for Episodes

### ISSUE THREAD

**Issue by ghost** [marcelveldt/script.skin.helper.service#111]
When an Episode is the current item, like in the Next Episodes widget, the ListItem.Premiered property displays a date where the year field seems to default to 0. This property works fine outside of the SkinHelper widgets.  For example, the date returned for an Episode should look something like 11-01-2017, but instead is returned as 11-01-0.

**Comment by Angelinas1** [comment]
try new version, if you have same isue please open new isue
