### ISSUE TITLE
Forced views sometimes fails

### ISSUE THREAD

**Issue by hawkeyexp** [marcelveldt/script.skin.helper.service#113]
Hi Marcel,

it seems forced views sometimes fails - primary on shows / episodes. Can you possible have a look on it ?

Guilouz from EstuaryModV2 has confirmed this behaviour.

https://forum.kodi.tv/showthread.php?tid=306757&pid=2680512#pid2680512

**Comment by Angelinas1** [comment]
I tested and all forced view work ok...
I close for now, new version is in the air....
