### ISSUE TITLE
Serious Widgets issues

### ISSUE THREAD

**Issue by Blurayx** [marcelveldt/script.skin.helper.service#114]
Next Aired 6.0.5. All TV show are showing 
<a href="https://imgur.com/KqDPDU7"><img src="https://i.imgur.com/KqDPDU7.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/pqgy4Nx"><img src="https://i.imgur.com/pqgy4Nx.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/6IrGGnU"><img src="https://i.imgur.com/6IrGGnU.png" title="source: imgur.com" /></a>

Widgets home screen: Episodes Airing Today.  6 TV shows missing
<a href="https://imgur.com/Q9MfLQR"><img src="https://i.imgur.com/Q9MfLQR.png" title="source: imgur.com" /></a>

Next Aired 7.0.1: mega machines tv Show widget missing

**Comment by Angelinas1** [comment]
try new version...

**Comment by Blurayx** [comment]
No longer using Next Aired. I'm now using jurialmunkey: plugin.video.themoviedb.helper. Next Aired has been reconfigured and integrated to work with Artic Horizon skin 😀
https://github.com/jurialmunkey/plugin.video.themoviedb.helper
