### ISSUE TITLE
Invalid media type "genre" / Unknown Video Info Key "progress"

### ISSUE THREAD

**Issue by HeresJonny** [marcelveldt/script.skin.helper.service#123]
I'm getting a ton of these errors since a few months. Kodi L latest nightly. Skin.helper.service 1.1.24.

23:10:14.466 T:1156 WARNING: Invalid media type "genre"
23:10:14.467 T:1156   ERROR: NEWADDON Unknown Video Info Key "progress"

Skin.helper.service is the only addon that references "newaddon".

**Comment by SerpentDrago** [comment]
I've also been unable to solve this . 

SO MANY of these in the log .. SOOO many

**Comment by opscc** [comment]
fixed by deleting line    [ or something equivalent such as 'if kodi.version==18.0' blah,blah ]  
    "progress": item.get('progresspercentage')
in file
   "script.module.metadatautils\lib\helpers\kodidb.py"

**Comment by Angelinas1** [comment]
fixed
