### ISSUE TITLE
Issue with Tools - Set Kodi Setting

### ISSUE THREAD

**Issue by nonJon** [marcelveldt/script.skin.helper.service#125]
Not able to set anything other than booleans with this functionality.
`RunScript(script.skin.helper.service,action=setkodisetting,setting=[NAME OF THE SETTING IN GUISETTINGS],value=[VALUE FOR THE SETTING])  `

For example, this works:
`<onload>RunScript(script.skin.helper.service,action=setkodisetting,setting=myvideos.extractchapterthumbs,value=false)</onload>`

This does not:	
`<onload>RunScript(script.skin.helper.service,action=setkodisetting,setting=myvideos.selectaction,value=3)</onload>`

Cannot set ints or strings.  Tested on Krypton and Leia.

**Comment by nonJon** [comment]
Found the problem. The function setkodisetting() in main_module.py:

elif  is_int:
       value = '"%s"' % value

Should be:

elif  not is_int:
       value = '"%s"' % value

**Comment by AnonTester** [comment]
Fix added to https://github.com/kodi-community-addons/script.skin.helper.service/pull/132

**Comment by Angelinas1** [comment]
Fixed in 
https://github.com/kodi-community-addons/script.skin.helper.service/commit/0a4cd7514366b97ac542a87f29a6a408ad19c46e
