### ISSUE TITLE
Localised Date Format for ListItem.LastEpisode.Airdate

### ISSUE THREAD

**Issue by abbaskip** [marcelveldt/script.skin.helper.service#126]
Currently I'm playing with a skin that shows when a series ran, so I have 

`<label>$INFO[Window(Home).Property(SkinHelper.ListItem.Premiered)] - $INFO[Window(Home).Property(SkinHelper.ListItem.LastEpisode.Airdate)]</label>`

My issue is, whilst the first date is in the correct local format, the latter isn't (and is in American). So I end up with things like:
20/10/14 - 3/31/16

As the date range.

**Comment by Angelinas1** [comment]
Now working ok !
DD-MM-YYYY
