### ISSUE TITLE
LyreBird : Backup from Windows OK but Restore to Android failed !

### ISSUE THREAD

**Issue by VERSEAU44** [marcelveldt/script.skin.helper.service#130]
Hi !
I use KODI on Windows and Android devices
Before, I used to configure Mimic skin on my PC and then I made a backup of its configuration (via "Skin Helper Skin Backup Service") that I restored on other devices
But since the switch to KODI 18 (and therefore LyreBird that replaces Mimic), the backup of the PC works (See attached ZIP) but not the import in Android : any idea ?
Kind regards
[Lyrebird Skinbackup (2019-09-12 15.49.33).zip](https://github.com/kodi-community-addons/script.skin.helper.service/files/3606306/Lyrebird.Skinbackup.2019-09-12.15.49.33.zip)
[Lyrebird Skinbackup (2019-09-12 15.49.33).zip]

**Comment by Angelinas1** [comment]
New version is on github
