### ISSUE TITLE
Estuary - How i can add setting for "skinhelper.autoclosevideoosd" 

### ISSUE THREAD

**Issue by DjDiabolik** [marcelveldt/script.skin.helper.service#133]
I have installed Skinhelper on my kodi setup....... i use the stock estuary.
After install it whit all dependecy how i can add this setting to currently skin for set the value correctly from skin ??

**Comment by Angelinas1** [comment]
Please use forum for this...
https://forum.kodi.tv/showthread.php?tid=235676
