### ISSUE TITLE
Problems with http://localhost:52307/ calls (getpvrthumb and getartwork) on Kodi 18

### ISSUE THREAD

**Issue by Bruur** [marcelveldt/script.skin.helper.service#136]
I'm running into problems on Kodi 18 (in CoreELEC) when using the local webservice call http://localhost:52307/getpvrthumb, which the Skin Helper Service supplies using CherryPy. On Kodi 17 it works like charm, but on Kodi 18 it doesn't work well.

For example it is used in OpenInfo, but in Kodi 18 it doesn’t show clearlogo’s. It defaults to presenting titles of movies and TV shows as text. I did some digging and OpenInfo (a ExtendedInfo fork, I know it's not maintained, but it still works). It uses the following line to retreive the clearlogo’s (I use the Netflix view by the way):

In: _script.extendedinfo-DialogVideoInfo-Netflix.xml_:
`<texture background="true">http://localhost:52307/getpvrthumb&amp;title=$ESCINFO[Window.Property(movie.Title)]&amp;type=clearlogo&amp;mediatype=movies</texture>`

I'm not sure why the **getpvrthumb** method is used, but I've tried an alternative call using **getartwork** and this doesn't work as well:

`http://localhost:52307/getartwork/?imdbid=tt0087182&amp;mediatype=movies&amp;type=clearlogo`

The method **getthumb** works by the way, but this only returns the first image from a Google Search. I need the clearclogo which is gathered using MetadataUtils, from Fanart.tv. And, I've configured it by the way with my own personal API key, so that can be scratched off the list of probable causes too.

I've been tinkering around in the file **webservices.py** and it seems to me that the problem is somewhere in the **handle_artwork** and/or **handle_image** function.

Could somebody find out how to fix this problem? So I can retrieve clearlogos again using a http://localhost:52307/.. call. Any alternative solutions are welcome as well!

**Comment by Angelinas1** [comment]
getpvrthumb with new version just tested in browser with code...and working ok, have banner in browser and in kodi list.
http://localhost:52307/getpvrthumb?title=avatar&type=banner
getartwork have isue......
I will close this isue for now..... tnx for understanding
