### ISSUE TITLE
Skin Helper and Matrix and Dependencies

### ISSUE THREAD

**Issue by n0valis** [marcelveldt/script.skin.helper.service#137]
I am try to install the skin helper service from your Matrix Repo but the instalation fails because dependencies cannot be resolved.
Beatufuksoup, Cherrypy, thetvdb and musicbrainz.
Same if I download the zip from here.

Anything I missed?

**Comment by Angelinas1** [comment]
For Kodi 19, I upload only two zip file and you can update from your kodi, repository.marcelveldt.
-"script.module.metadatautils" version="1.0.35"
-"Skin Helper Service" version="1.1.31"

For missing Dependencies, you can download manual and install "from zip" in your Kodi Matrix, from other participant in this project. (try version from AnonTester)
I dont use Beta version, and can't test, so i just upload version of script for Leia version.
