### ISSUE TITLE
Update for Kodi 19

### ISSUE THREAD

**Issue by Machou** [marcelveldt/script.skin.helper.service#144]
Hello

Can you update for Kodi 19 please ;)

![image](https://user-images.githubusercontent.com/1043650/120576636-69088e80-c423-11eb-9ad1-5f15ac75ba7e.jpeg)

**Comment by Angelinas1** [comment]
Install from zip...
https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/repository/repository.marcelveldt/repository.marcelveldt-1.0.3.zip

**Comment by Machou** [comment]
> 
> 
> Install from zip...
> https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/repository/repository.marcelveldt/repository.marcelveldt-1.0.3.zip

Is working For Kodi 19 with OSMC Skin ?

**Comment by Angelinas1** [comment]
yes...try and write comment here :)

**Comment by Machou** [comment]
> Install from zip...
> 
> https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/repository/repository.marcelveldt/repository.marcelveldt-1.0.3.zip

Is working for Kodi 19 - OSMC 2020.11-1 - Kernel Linux 5.10.32-1

Thanks :)
