### ISSUE TITLE
crashing in Kodi 18.6 

### ISSUE THREAD

**Issue by jcollum** [marcelveldt/script.skin.helper.service#148]
`No module named helpers.animatedart` in the stack trace, that looks like the root cause. Installed Kodi a few days ago with the instructions here: https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux (Ubuntu)

**Comment by Angelinas1** [comment]
You use old version...update from
https://github.com/kodi-community-addons/repository.marcelveldt/tree/master/olderversions

**Comment by jcollum** [comment]
You should talk to the Kodi team about getting their code updated because the one that ships with Kodi is out of date
