### ISSUE TITLE
Not for the faint hearted. 

### ISSUE THREAD

**Issue by adamosborne83** [marcelveldt/script.skin.helper.service#152]
I hope you can help, see the below issues that I had whilst using Venom and auramod. 

Thanks. 

https://github.com/123Venom/plugin.video.venom/issues/169

**Comment by Angelinas1** [comment]
That error is know...Kodi isue in Matrix version
Just disable debuglog in setings for script.module.metadatautils
And error will be removed in standard log.
shs not cosing your isue with venom....

**Comment by adamosborne83** [comment]
> That error is know...Kodi isue in Matrix version Just disable debuglog in setings for script.module.metadatautils And error will be removed in standard log. shs not cosing your isue with venom....

Thabk you for your reply. Apologies for my ignorance, but will this allow the files to play?
