### ISSUE TITLE
Updating Skin while in same skin

### ISSUE THREAD

**Issue by jojobrogess** [marcelveldt/script.skin.helper.service#154]
>Skin Helper Service --> Exception details: Type: RuntimeError Value: Unknown addon id 'skin.auramod'. Traceback: Traceback (most recent call last):
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\main_service.py", line 73, in check_skin_version
                                                       skin_addon = xbmcaddon.Addon(id=skin)
                                                   RuntimeError: Unknown addon id 'skin.auramod'

Screen went black, pressing back returned me to main screen with all items discolored and "broken"(gray boxes for images).
I have a full log if you want that, but it's pretty boring. 

I had to close and reopen Kodi to resolve this.

**Comment by Angelinas1** [comment]
Just try it from https://github.com/SerpentDrago/skin.auramod
working as expected

Custom InfoLabels
    Window(Home).Property(SkinHelper.skinTitle) :+1: 
Aura[COLOR cyan]MOD[/COLOR] - Version: 1.1.9

**Comment by jojobrogess** [comment]
Sorry to bother!

It was probably something on my end.
I've just never seen it before and thought it was new.
