### ISSUE TITLE
NextAired TV Shows widget issues

### ISSUE THREAD

**Issue by Nessus85100** [marcelveldt/script.skin.helper.service#18]
@marcelveldt I tested this 110da78cb8f2634ca8445ef95d3afa0cc076284c and everything working fine except that the `ListItem.Art(poster)` is empty. But my main issue is that the list returns only shows that airing the current day/date. My goal for this was to show a list with all the shows (that are in the library), when they airing. That way you can see which day and date a show is airing.
Is that possible ?.

Thanks
Nessus

**Comment by marcelveldt** [comment]
Thanks for testing this. Í've just pushed a fix for the missing Poster art to Git.

Well, I understand what you're saying. The NextAired script only provides properties for tvshows that are airing today but what you want is "next airing tv shows", which will list the tvshows on air date...
I'm not sure this is even possible with the nextaired script, I might have to code support for that myself

**Comment by Nessus85100** [comment]
NextAired script has support for that. You can enable up to 15 days NextAired info in addon's settings and it shows those info in TVGuide via the script-NextAired-TVGuide2.xml file.

**Comment by marcelveldt** [comment]
Yeah, I know but how to get that info outside of Nextaired script ? there aren't any window properties available for it as far as I can see

**Comment by Nessus85100** [comment]
I see. Well, it will be great to have this. I will leave this open in case you decide to add the code support for it.

Thanks
Nessus

**Comment by marcelveldt** [comment]
I looked at this. There's no way to communicate with the nextaired script to get the info. All logic is inside that addon itself and only the aired today is exposed in the window props.

As I already have the TMDB api integrated in my script I did some quick tests.
What i can do is build these listings based on TMDB info. So drop the nextaired-addon requirement and just grab the info from TMDB. That way I can provide you with two widgets:

1) TV shows airing today (matching shows in the library)
2) TV shows airing in the next 7 days (mathing library_

These will be available as cdynamic content paths so you can use them as widgets or show them directly in the video library.

Does this sound like a proper solution to you ?

**Comment by marcelveldt** [comment]
BTW: I can also ask the author of nextaired script if he can create a plugin path entry to be used in widgets?

**Comment by Nessus85100** [comment]
> That way I can provide you with two widgets:
> 1) TV shows airing today (matching shows in the library)
> 2) TV shows airing in the next 7 days (mathing library)

That will be great. Also if it's not so much trouble, if you can extend the second one to the next 15 days will be great.

> BTW: I can also ask the author of nextaired script if he can create a plugin path entry to be used in widgets? 

Whatever is more convenient to you. I just want to use that kind of list as widget.

Thanks
Nessus

**Comment by mgonzales71** [comment]
Marcel, decided to try the "My TV Shows Airing Today" widget after reading this and when I select any items from the widget I get this in the log:

ERROR: Keymapping error: no such action 'playmedia("")' defined

playmedia is a builtin function, right?   the keymapping part confuses me.

any thoughts?  thanks!

**Comment by marcelveldt** [comment]
Hi Nessus, just a quick note that I've added nextaired support to skinhelper. It now has a widget/plugin listing for the next airing episodes

**Comment by Nessus85100** [comment]
Works fine although i dont see anywhere in the README how the ListiIems properties are and shows fanarts are also empty.

These are the ListiIems properties that currently i use in my code:
$INFO[ListItem.Property(NextNumber)] == Season/Episode number eg '01x01'
$INFO[ListItem.Property(NextTitle)] == Episode Title
$INFO[ListItem.Property(NextDay)] == Airing date localized format eg 'Mon, Jul 30, 2016'
$INFO[ListItem.Property(ShortTime)] == Time the episode is aired, eg. "20:00" or "08:00 PM" 
$INFO[ListItem.Property(Network)] == Name of the TV Network
$INFO[ListItem.Property(Fanart)] == TV Show's fanart

I use these with your [TV Shows Airing Today](https://github.com/marcelveldt/script.skin.helper.service#my-tv-shows-airing-today) widget, but they are returning empty with the new widgets.

BTW what's the difference for the Unaired and the Next airing episodes ?. 

PS. There is a typo in the README in the `plugin://` Next airing episodes. `unairedepisodes` it should be `nextairedepisodes`

Cheers
Nessus

**Comment by marcelveldt** [comment]
It will only use the default Kodi properties for the listitems, meaning they will be presented as normal episodes:

ListItem.Season
ListItem.Episode
ListItem.Studio
ListItem.Art(fanart, poster etc.)

So just treat the widget as any normal episodes widget and you will have all info, even the episode thumb if it's already present on tvdb.

The only thing I can think of is to add some additional properties for the airtime and such.
Currently the ListItem.FirstAired field is filled with the airing date.

I will fix the readme, thanks for the catch

**Comment by Nessus85100** [comment]
Yes, they are working fine as default Kodi info labels. The only issue is the date and time.
I mean the `ListItem.Premiered` it gives a simple not so good looking format like this: 30-07-2016.
A better looking format like... 'Mon, Jul 30, 2016' it will be great and also the airtime is very useful since these are Next Airing info.

In any case, thanks a lot for adding this.

Cheers
Nessus

PS. So, what's the difference between Unaired and Next Airing episodes ?.

**Comment by Nessus85100** [comment]
More on this...
First of all the widget takes ages (2-3 mins) to load on first Kodi open of the day. Secondly for some reason the `ListItem.Art(tvshow.poster)` returns the Season poster and it falls back to TV Show poster when there is no Season poster.

I saw the additional properties that you added about the day and time (although time is not following the Kodi regional time format), but still the `ListItem.Premiered` (`ListItem.FirstAired` is empty for me) it gives this ugly... dd-mm-yyyy format for the date. If you change the `ListItem.Property(airday)` property to something like this one... "Mon, Jul 30, 2016" it would be great.

Thanks
Nessus

**Comment by marcelveldt** [comment]
Hi Nessus, take a look at my latest changes regarding this. I think it's now pretty much what you mean.

**Comment by Nessus85100** [comment]
I am getting a script error with the latest commit... http://pastebin.com/WNcFbXF0

I have installed all the needed modules including the [script.module.thetvdb](https://github.com/marcelveldt/script.module.thetvdb)

Thanks for continue on this

Cheers
Nessus

**Comment by marcelveldt** [comment]
Maybe better to install my repo which has all the needed stuff.
The error you're getting now is that you're still missing modules or they're installed incorrectly

**Comment by Nessus85100** [comment]
I manually remove everything (even from package folder) and installed from your repo.
Everything were installed fine from there but and now i get a different error...
http://pastebin.com/ewviBXBA

**Comment by marcelveldt** [comment]
sorry, that was my fault, checked in something in error. It should now be okay

**Comment by Nessus85100** [comment]
Yes, it's working fine now!
You are right. The info and the posters are as they supposed to be.

If i cant mention only one small thing is that is taking the systems short date format and the 12-our clock time format. I think is better to use the long date format and the 24-our clock format.

Currently it shows like this:
DC's Legends of Tomorrow
2x7. Invasion!(4)
01-12-2016 at 8:00 PM

When in my system it suppose to show like this...
DC's Legends of Tomorrow
2x7. Invasion!(4)
1 December 2016 at 20:00

or disregard completely the system regional format and show it like this...
Dec 1, 2016 at 20:00

In any case thanks a lot for making this and of course for all you great work on this great script

Cheers
Nessus

PS. Any chance for my other requests. No hurry of course. Whenever you have the time.

**Comment by marcelveldt** [comment]
It should follow the date / time format you've set in Kodi. Can you confirm ?
It works on my end (Dutch) like it should and looking.

Also take a look at the complete list of properties:

https://github.com/marcelveldt/script.skin.helper.service/wiki/Listitem-Properties---Tvshows

**Comment by Nessus85100** [comment]
Well, it works properly but it shows the Short date format...

![image](https://cloud.githubusercontent.com/assets/1375649/22926753/aa5e1c8a-f2b6-11e6-8962-15dfb0f7454a.png)

What i wanted is to show the Long date format and get this....
**Suits
6x14. Admission of Guilt
Wednesday, 15 February 2017 at 22:00 on USA Network**

Currently with script's properties i can achieve this... 
**Suits
6x14. Admission of Guilt
Wednesday, 15-02-2017 22:00 on USA Network**


Anyway, it's not a big deal. If you cant do it's fine otherwise leave it like it is. No worries.
In any case you can close this issue.

Thanks
Nessus

**Comment by marcelveldt** [comment]
I've added an additional property airdate.long to the properties. 
I will place the updated version (1.0.17) of the tvdb module on my repo later tonight.

**Comment by Nessus85100** [comment]
Although the tvdb module is updated to 1.0.17 the airdate.long property is empty for me!

**Comment by marcelveldt** [comment]
yes, because the data is cached... you will have to wait a few days until the cache is refreshed or just manually wipe the simple cache db file

**Comment by Nessus85100** [comment]
Still empty!. I wipe out the simplecache.db and after 2-3 hours still not working.

This is the code that i use:
`$INFO[Container(25).ListItem.Property(AirDay),,$COMMA]$INFO[Container(25).ListItem.Property(AirDate.Long)]$INFO[Container(25).ListItem.Studio, on ]`
