### ISSUE TITLE
script errors .. recentsongs / recentplayedsongs

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#19]
running latest from GIT - have been noticing the following errors on startup
Kodi 15.2 rc3 on Win 10 x64

http://pastebin.com/3JrwrEV5

no urgency - just throws a couple exceptions and alert notifications on startup.

thanks for all the hard work Marcel!

as always - let me know if I can provide any additional info, etc

M

**Comment by marcelveldt** [comment]
This should all be fixed in recent versions
