### ISSUE TITLE
Give option to change the webservice port in settings

### ISSUE THREAD

**Issue by alibbaba** [marcelveldt/script.skin.helper.service#21]
Can you create a option in settings for the webservice port option. Right now the port is 8888 . This will interfere if the user is already using another app outside Kodi with same port.  Also, a notification in Kodi will be nice that this service is using port 8888 when user fist installed the service.

I had to dig around quite a while to find the real problem. Now i change the port to different one and the problem solved.
https://github.com/marcelveldt/script.skin.helper.service/blob/master/resources/lib/WebService.py#L14
Thanks for your great work and your consideration of the problem.

**Comment by marcelveldt** [comment]
The best thing I can do is here is to change the port to a very high unused port, something like 52300 or something.

This is because the image webservice will be used by skinners inside a image control inside lists and they have no control over the port.

**Comment by marcelveldt** [comment]
default port is changed to 52307 and a confirmation about this will be printed in the kodi log.
