### ISSUE TITLE
Remove/Improve local image cache

### ISSUE THREAD

**Issue by ghost** [marcelveldt/script.skin.helper.service#26]
Wanted to get some feedback on this before I start coding it up and realise I'm making a huge mistake :smile:, but I can't see the purpose of caching the pvr images the script retrieves locally and it is causing some minor issues...
1. Wasting space - on devices with limited storage, caching the images locally is more than doubling the space needed for each image as Kodi also caches the images, but its versions are the optimised/shrunk .tbn versions
2. Slightly slower - at the moment the script searches for the image, downloads it, then (if I'm reading the code right) passes the local URI to Kodi. Which then itself loads, optimises and saves the image. Rather than passing the remote URI to Kodi to download-optimise-save directly
3. Old images if Skin Helper cache is deleted - because Skin Helper saves the downloaded images with the same name each time, and because (from what I understand and have seen from a quick test of this) Kodi decides which of the images in its cache to load based on the filename, once Kodi has cached, say, the thumb for a PVR item, even if Skin Helper downloads a new thumb Kodi will still use the old one it has cached as the filename is the same.

The obvious solution to me would be to save the remote filename that Skin Helper finds into the pvrdetails.xml file, and to provide that remote URI to Kodi when the skin requests the relevant image. That way, only Kodi's cache version of the image is downloaded, Kodi should take care of all downloading of the image, and if Skin Helpers cache is cleared and a newer image found that will be used by Kodi.

That's unless I'm missing something in the way the cache is designed to work, though ;) Any feedback or insight is welcome before I put the time into coding this!

**Comment by marcelveldt** [comment]
Some people like to have the images locally, from what I believe these are users with a very limited internet connection. By default the script won't download any images and just uses the Kodi texture cache by passing the external url. The problem is when the internet connection is down the Kodi texture cache will fail too because it's trying to do a HEAD request to the image URL and only after it gave up it will show the existing image in the cache...

So, the only reason I provided an option to download the images is for the above scenario where users want to have the images locally. Besides that, some people just want to scrape the images theirselves and place them in the pvr folder so the script will also check for any existing images in the folder.

If you have any improvements, please let me know

**Comment by ghost** [comment]
Thanks for your insight into this. From my understanding of what you've said, the way it should work is the way that I would prefer that it does work (which is to say returning to Kodi the remote path rather than the VFS path to the locally cached image) - my next job will be to work out why it isn't working that way on my systems and, admittedly, with version which are now 7+ days out of date (which, with how fast this script is evolving, is an eternity!)

**Comment by marcelveldt** [comment]
Yeah, it should indeed work exactly like you said. The script doesn't download anything by default (you can turn that on optionally in the addon settings). It just passes the remote path to Kodi and let the Kodi texture cache handle the rest. This works fine in most cases and no need to waste diskspace. 

The only thing that does get saved is an xml file in which I save all the details that were scraped. This is to cache the details found.

**Comment by ghost** [comment]
Sorry, I meant to come back and update/close this :blush: 

I found the option:- "Download artwork for pvr recordings" (I haven't looked into the guide images yet) - I misunderstood what it did, thinking it toggled whether skin helper would go look for pvr thumbs. Obviously, it enables actually downloading them.

(However, it is enabled by default:- `<setting id="cacheRecordings" type="bool" label="32101" default="true" visible="Skin.HasSetting(SkinHelper.EnablePVRThumbs)"/>` ;))

Thanks for the assistance, and sorry for the confusion :)

**Comment by marcelveldt** [comment]
Oops, never noticed it was enabled by default 😃. I will change that, thanks.

**Comment by Morphy99** [comment]
I've just been looking at folders that need cleaning and noticed my pvrthumbs dir is 1.8gb :scream: 
Am I ok just to wipe this? 
I've been looking at [Kcleaner](http://forum.kodi.tv/showthread.php?tid=307919) addon and was wondering if maybe you had time to work with him on adding support for your addons within?

**Comment by marcelveldt** [comment]
Yes you can delete that folder. The latest versions do not even use that approach anymore.

**Comment by Morphy99** [comment]
Great thanks for the info. I noticed musicartcache has some files with recent dates or is that deprecated now too?

**Comment by marcelveldt** [comment]
also deprecated
