### ISSUE TITLE
FR: tunefind support

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#32]
Had suggested this to Phil65 for extended info back in October but never heard back from him so asking if you may be interested in adding this as a feature to skin helper:

support for TuneFind 

They have an API that should allow this feature easier then scraping a site

http://www.tunefind.com/api 

Feel free to veto/ignore - figured it never hurts to ask/suggest :smile: either way I will still love and enjoy your script and skin! 

thanks for all the great work!

Mario

**Comment by Angelinas1** [comment]
Add in  version="1.0.50"
https://github.com/kodi-community-addons/script.module.metadatautils/commit/71cb726e9d6404eedb6599e9cc489ac5eed40262
