### ISSUE TITLE
Default Browse path  option

### ISSUE THREAD

**Issue by Blurayx** [marcelveldt/script.skin.helper.service#34]
I'm using Kodi Skin Eminence 2 MOD. and it has a feature where I can save or restore the skin settings.
I requested from the developer to have a setting to create a default folder. but he said it's the limitation of skin helper services. will it be possible to add this feature in skin helper so that the developer can add a default browse path option.

Thanks

**Comment by marcelveldt** [comment]
What do you mean exactly by this ?
Do you mean a default starting path ?
