### ISSUE TITLE
V1.0.32 Causes 44 Second Delay at Startup

### ISSUE THREAD

**Issue by imadunatic** [marcelveldt/script.skin.helper.service#36]
I've been playing with Jarvis for a few days, posted this issue over on the kodi forums, but I didn't want to detract from the cadence of that conversation if this is one off problem (which it oddly seems to be). I've been able to reproduce with a couple different installs of both Jarvis Beta 5 and Helix 15.2.

This is my process:
- Install Kodi
- Let update
- Restart Kodi
- Install Titan Skin (so that skin helper is installed as dependency through kodi repo)
- Restart Kodi

On this boot up, skin helper service starts almost immediately (within 1 second or less) as seen by the logs:
- Jarvis Beta 5 Log with Skin helper 1.0.23: http://pastebin.com/iDt0jecJ
- Helix 15.2 log with Skin Helper 1.0.23: http://pastebin.com/XiEifZ5M
- Next, install Emby Beta Repo (only) which will trigger an update to Skin Helper 1.0.32
- Restart Kodi (sometimes hangs after installing Emby repo from zip and Skin Helper updating, not sure if this is related). 
- Wait for kodi to finish shutting down
- Restart Kodi

On this boot up, skin helper service starts after a consistent 43-45 second delay (which also delays loading of other services such as Emby): 
- Jarvis Beta 5 Log with Skin Helper 1.0.32: http://pastebin.com/W5xSE5H4
- Helix 15.2 with Skin helper 1.0.32: http://pastebin.com/qQGryFpE

I've done no other customization on these installs, I am not actually using the Titan skin (selecting "no" when asked if I'd like to keep this skin) and I've not installed any other addons at all to try and narrow this down. My current machine is Windows 10 and these are both **portable installs**. 

I do have another 15.2 main install that I use, but I'm leery to update that to 1.0.32 for testing in case it causes the same behavior. Can I simply copy the current script.skin.helper.service folder from the main install and keep it in my pocket in case 1.0.32 causes a similar issue there? 

Thanks for any and all help.

**Comment by imadunatic** [comment]
So, I just installed 1.0.32 on my main install with the same symptoms. I don't use a skin on Helix that requires it so I just uninstalled it after testing.

**Comment by imadunatic** [comment]
A little more testing... Tried to replicate this on a Windows 7 machine and the behavior doesn't exist. At this point, I'm assuming it's a Windows 10 issue, or specific to my server. I have another windows 10 machine that I plan to test this theory on later today. 

I've also simplified the process:
- install kodi
- install skin helper addon from zip file
- note 43-45 second delay (also, Kodi will not exit cleanly after installing skin helper, I _think_ this may be caused by not letting skin helper or kodi finish tasks after installation)

Edit: I should note that I retested this morning using 16RC1 on both the Windows 10 machine and Windows 7 machine. The windows 10 machine exhibited the 44 second delay, the windows 7 machine did not.

**Comment by marcelveldt** [comment]
Thanks for your very well documented test results. In fact another user mentioned this issue too on the forums and I couldn't replicate. No I'll have to try if I can find the cause.

My dev machine is windows 10 x64 and doesn't have this issue.
Is your win10 machine 32bits or 64 bits ?

**Comment by marcelveldt** [comment]
Oh, one more question... Could it be that some other service is delaying the start of skinhelper ?
Did you try this on a completely virgin install with only skinhelper installed ?

**Comment by imadunatic** [comment]
@marcelveldt , 

My windows 10 machine is 64 bit, and the windows 7 machine is 64 bit. 

The logs listed in the first post were virgin installs with only the titan skin (I'm sure you're very familiar with the dependencies this installs) and then the Emby Beta Repo (so that the script would update through a repo instead of manually). 

The tests I did this morning were virgin installs of Jarvis 16RC1 on the Windows 10 and the windows 7 machine with only the skin helper installed via zip file (manually retrieved from Git, then installed via kodi-install from zip file), no other addons or repo's were installed to try and keep the install as sterile as possible. 

Also, I enabled verbose logging for the skin helper; unfortunately, the delay appears to be the actual starting of the service, so no additional logging takes place during the 44 second delay. Is there any other verbose logging I can enable in Kodi that might shed some light on what is happening between the 

```
18:51:28 T:11880  NOTICE: UDP: Listening on port 9777
```

and the starting of the service? 

I'm hoping to have time this weekend to install this on one of my Android boxes and see if the issue persists there. I've currently only been able to replicate this on one machine. My wife is currently using the laptop, but once she's done I plan to install kodi on it (It's windows 10, 64 bit as well) and see what the outcome is. If it's relevant, I'll post back here.

**Comment by imadunatic** [comment]
Just installed on a windows 10, 64 bit laptop. 
- virgin (full) install of V16RC1
- allow to update all addons
- restart Kodi
- Install skin helper service from latest Git (30 minutes or so since last merge-commit)
- Shows same 43-45 second delay

So I've finally been able to replicate on another machine, obviously the problem is that it's the same OS you're using and not exhibiting the same error.

Here are the logs: http://pastebin.com/NFiKqpwc

If there is anything I can do to help, please let me know. This is currently only on my Jarvis portable install that I'm trying to familiarize myself with before turning loose in the wild, so I'm more than happy to do any testing/reporting that may be of any assistance.

**Comment by marcelveldt** [comment]
Turns out my develop machine was still at 16.0 beta 4.
Now installing RC1 to to test it. Hopefully I'm able to replicate the issue

**Comment by marcelveldt** [comment]
OK, virgin install of the Kodi 16 RC1, emby beta repo and latest skinhelper beta.
Starts instantly so stil not able to reproduce.

In the addon settings you can enable verbose debug logging. That might help to shed a light on this.

**Comment by imadunatic** [comment]
Ok, did another virgin install of RC1, install latest from zip file, enabled debug logging and did a full cycle, here are the logs: http://pastebin.com/jgAWtPb7

I'm going to enable verbose logging for all of Kodi and try to pick through the logs and see if anything relevant shows up. If my wife's laptop didn't exhibit the same behavior I would chalk this up to being a corner case on this machine only.

**Comment by marcelveldt** [comment]
Thanks for the log. Nothing weird shows up in this one too. There must be some process blocking the startup of the skinhelper.

You can disable verbode logging again in the addon, it's not needed.
Is it possible to enable Kodi debug logging in the settings ?
Once you enabled it, restart Kodi to see what is starting (and blocking) before the skinhelper service starts.

**Comment by imadunatic** [comment]
Should I enable component specific logging for anything in Kodi or just debug logging?

**Comment by marcelveldt** [comment]
just debug

**Comment by imadunatic** [comment]
Kodi Debug Logs: http://pastebin.com/tNeagyWZ

**Comment by marcelveldt** [comment]
OK, I think I have found the issue, thanks for the logs.

Can you test with the latest version of the script from Github ?

**Comment by imadunatic** [comment]
Yep. You got it. Starts in 2 seconds or less now. 

Log Sample: 

```
06:17:18 T:7732 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
06:17:18 T:7732  NOTICE: ActiveAE DSP - starting
06:17:18 T:7732  NOTICE: initialize done
06:17:18 T:7732  NOTICE: Running the application...
06:17:18 T:7732  NOTICE: starting upnp client
06:17:18 T:6516  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
06:17:18 T:6516  NOTICE: UDP: Listening on port 9777
06:17:20 T:7320  NOTICE: Skin Helper Service --> skin helper service version 1.0.33 started
06:17:20 T:7320  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
```

Thanks again for the help on this. I know it was a bit of a corner case....

**Comment by marcelveldt** [comment]
Great it is resolved. Thanks for your help debugging the issue!
