### ISSUE TITLE
Try to fix "ERROR in BackgroundsUpdater" for artist

### ISSUE THREAD

**Issue by Angelinas1** [marcelveldt/script.skin.helper.service#38]
Marcel something wrong with new changes for latest changes for artist background 

21:00:51 T:2884   ERROR: Skin Helper Service --> ERROR in BackgroundsUpdater ! --> 'list' object has no attribute 'replace'
21:00:51 T:2884   ERROR: Traceback (most recent call last):
21:00:51 T:2884   ERROR:   File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\BackgroundsUpdater.py", line 54, in run
21:00:51 T:2884   ERROR:     self.UpdateBackgrounds()
21:00:51 T:2884   ERROR:   File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\BackgroundsUpdater.py", line 516, in UpdateBackgrounds
21:00:51 T:2884   ERROR:     self.setImageFromPath("SkinHelper.AllMusicSongsBackground","musicdb://songs/")
21:00:51 T:2884   ERROR:   File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\BackgroundsUpdater.py", line 297, in setImageFromPath
21:00:51 T:2884   ERROR:     image = artutils.getMusicArtwork(media.get('artist',''),media.get('album',''))
21:00:51 T:2884   ERROR:   File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\ArtworkUtils.py", line 966, in getMusicArtwork
21:00:51 T:2884   ERROR:     if not ignoreCache: albumartwork = getArtworkFromCacheFile("special://profile/addon_data/script.skin.helper.service/musicart/%s-%s.xml" %(normalize_string(artistName),normalize_string(albumName)))
21:00:51 T:2884   ERROR:   File "C:\Users\Lenovo\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\Utils.py", line 697, in normalize_string
21:00:51 T:2884   ERROR:     text = text.replace(":", "")
21:00:51 T:2884   ERROR: AttributeError: 'list' object has no attribute 'replace'

**Comment by marcelveldt** [comment]
thanks, will fix it right away.
apparently this has changed between isengard and jarvis
