### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by abeksis** [marcelveldt/script.skin.helper.service#40]
ERROR: GetDirectory - Error getting /Users/user/Library/Application Support/Kodi/userdata/library/video
ERROR: GetDirectory - Error getting /Users/user/Library/Application Support/Kodi/userdata/library/music 

ERROR: Error parsing boolean expression + [!stringcompare(Skin.String(home.widgetposters)

What could be the problem?

**Comment by marcelveldt** [comment]
This is not related to skinhelper addon... This is a skin error.
