### ISSUE TITLE
Not Pulling thumbnails for virtual folder groups from ServerWMC PVR plugin anymore

### ISSUE THREAD

**Issue by Pack3tL0ss** [marcelveldt/script.skin.helper.service#41]
Something appears to have changed.

The ServerWMC PVR plugin has the option to "group items" so rather than seeing 12 individual episodes of "Castle" in your recorded TV list, you would see a single listing for "Castle (12)".  Clicking it would display a listing of all the individual episodes.

In previous releases I figured out a way to use this plugin to automatically search for artwork and populate the artwork for these shows (So I'd get poster art etc when "Castle (12)" was highlighted.)  Essentially I configured the "stripwords" item in the settings file with (1);(2);(3);... and so on.  I went to (99) so as long as I didn't have a show with over 99 recordings, show art would populate.

Then a couple of shows I gathered fan-art manually, these were just shows that are local, or didn't have sporting event categories that don't have any show data available online (Local morning news, College Wrestling, and a special folder "Recording Now" which is a where shows live while actively being recorded).  All of those folders have custom art, and would show up nicely.

It appears the "stripwords" doesn't have the same impact now though, so the way I'm using it doesn't function and I'm back to generic folder icons for any groupings (the virtual folders with the (#) )

Kodi.log logs as I highlight a show (virtual folder).
`22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> setPVRThumb dbID--> Childrens Hospital (2)  - path: pvr://recordings/active/Childrens Hospital (2)/`

This is the part I'm not familiar with yet.  The special path pvr:// it obviously isn't stripping the (2), but not sure if that is the cause.  Again "Childrens Hospital (2)" is actually a virtual folder - serverWMC is grouping all of the Childrens Hospital episodes in this folder.

`22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> getPVRThumb for Childrens Hospital  -->
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> getPVRThumb no cache found for dbID--> childrenshospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> pvr thumbs path --> special://profile/addon_data/script.skin.helper.service/pvrthumbs/Childrens Hospital/`

The line above leads me to believe at least a portion works as it did.  It knows to look in the folder "Children Hospital" and not "Childrens Hospital 2", but it appears to be looking for dbID "childrenshospital", but it set `setPVRThumb dbID--> Childrens Hospital (2)` in the prior log entry.  I'm curious if the stripwords setting's impact comes too late if the dbID mechanism is the new part of this process.  It appears it may set the dbID based on the show title (without honoring stripwords) then it looks at stripwords and does the lookup (but I'm taking stabs at something I don't know all the mechanics of, hence the post)

`22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> thumbspath found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> thumb found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> poster found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> fanart found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> landscape found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> clearlogo found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> clearart found on disk for Childrens Hospital
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> extrafanart found on disk for Childrens Hospital`

And it finds all of the artwork in those folders, but artwork is no longer displayed as it was in prior releases.  

`22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> getJson - invalid result for Method VideoLibrary.GetTvShows - params: { "filter": {"operator":"is", "field":"title", "value":"Childrens Hospital "}, "properties": [ "dateadded", "file", "lastplayed","plot", "title", "art", "playcount","sorttitle", "mpaa", "premiered", "year", "episode", "watchedepisodes", "votes", "rating", "studio", "season", "genre", "cast", "episodeguide", "tag", "originaltitle", "imdbnumber" ] } - response: {u'limits': {u'start': 0, u'total': 0, u'end': 0}}
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> getJson - invalid result for Method VideoLibrary.GetMovies - params: { "filter": {"operator":"is", "field":"title", "value":"Childrens Hospital "}, "properties": [ "dateadded", "file", "lastplayed","plot", "title", "art", "playcount","streamdetails", "director", "resume", "runtime","plotoutline", "sorttitle", "cast", "votes", "showlink", "top250", "trailer", "year", "country", "studio", "set", "genre", "mpaa", "setid", "rating", "tag", "tagline", "writer", "originaltitle", "imdbnumber" ] } - response: {u'limits': {u'start': 0, u'total': 0, u'end': 0}}
22:25:45 T:140287156360960  NOTICE: Skin Helper Service --> getTMDBimage - TMDB match found for Childrens Hospital  !
22:25:46 T:140287156360960  NOTICE: Skin Helper Service --> get fanart.tv images for type: tv - id: 139941`

I have to step through a few to get all the logs from above many of them just show a single log entry:
`22:41:42 T:140287262160640  NOTICE: Skin Helper Service --> setPVRThumb dbID--> Bones (33)  - path: pvr://recordings/active/Bones (33)/
22:41:48 T:140287288747776  NOTICE: Skin Helper Service --> setPVRThumb dbID--> South Park (6)  - path: pvr://recordings/active/South Park (6)/
22:41:51 T:140287288747776  NOTICE: Skin Helper Service --> setPVRThumb dbID--> Marvel's Agents of S.H.I.E.L.D. (11)  - path: pvr://recordings/active/Marvel's Agents of S.H.I.E.L.D. (11)/
22:41:55 T:140287288747776  NOTICE: Skin Helper Service --> setPVRThumb dbID--> Drunk History (6)  - path: pvr://recordings/active/Drunk History (6)/`

I'm curious if there is a disconnect between the entries referenced above with the pvr:// path that keep the parens (# of episodes within the virt folder).  and the references to the special:// path to the pvrthumbs folder where the stripwords is honored and the parens are stripped.

So not necessarily a bug.  The plugin was obviously designed for a lot more than this very specific use-case, but curious if someone can identify and state "yes we changed the way we did X so now that wouldn't work the same way" and ideally what would if anything I can tweak to make it work again.

Plugin release is whatever is current in the current openelec stable, and same behavior on Kodi 16 on the OpenElec beta

**Comment by marcelveldt** [comment]
Strange, this logic hasn't been changed for a long time as it was working very well.
Is it possible for you to try this with the latest Git version ?

Just download the zip from git and manually overwrite the files in your addons folder.

You could also wait a few days because I'm about to push a new version to the kodi repo

**Comment by Pack3tL0ss** [comment]
It looks like for the most part everything came back.  I returned from being on the road Saturday and noticed that it was pulling the details correctly again for most of the shows.  

I still haven't wrapped my head around thumbnails/fanart for individual episodes, but that's a challenge presented by the ServerWMC plugin (skin-helper service see's them as all flat because the grouping of episodes isn't the actual folder structure).  Otherwise if I have 6 episodes for the show "BlindSpot" I get a virtual folder "Blindspot 6" - that's the issue that seems to have fixed itself with one of the more recent pushes.  The remaining challenge is an individual episode i.e. "Split the Law" shows up in the same flat structure in the skin-helper pvrthumbs folder.  Sometimes it's correctly associated with the show BlindSpot, but if the episode name is something that matches a common movie or some other show it occasionally pulls thumbs and fanart for the wrong thing.  It doesn't have the benefit of a tiered folder structure with the episodes under the show folder.

That's not an issue with your script it's a challenge presented by WMC/ServerWMC plugin, and I honestly haven't spent a lot of time trying to find ways to improve it... but if you have any ideas, I'm all ears.  

Thanks for the response
PL

**Comment by marcelveldt** [comment]
OK great that the main part is now resolved. You may also want to check out the addon options and look for the "title splitter". I think in your case you could try to use the " (" as the title splitter
