### ISSUE TITLE
Default widgets can be very slow to load initially

### ISSUE THREAD

**Issue by ghost** [marcelveldt/script.skin.helper.service#42]
Loading the default widgets on my system is currently taking around 7 minutes first time (obviously much better on subsequent launches when the data is cached.)

The delay is coming from the `detectPluginContent` function and skin helper's own widgets. For me, it's also only affecting the music widgets.

From what I can see, though `detectPluginContent` is only requesting one item from the plugin in the JSON request, that isn't passed on Skin Helpers widget builder, which is building - judging from the logs - 100 items:

`NOTICE: Skin Helper Service --> getPluginListing-RECOMMENDEDSONGS-100-None--False -- no cache, quering json api to get items`

The slowness is caused because, as part of building those 100 items, Skin Helper is going off to find artwork for each of them via the `getMusicArtwork` function. With a hundred items, this takes a lot of time.

I'm not sure what the best way is to tackle this. The most obvious, to me, would be to adjust the plugin path within the `detectPluginContent` to change any limit= to 1, though that's not the easiest thing to do and I don't know how that might adversely affect the plugins own cache. There could well be better ways though!

I'm happy to make any changes and PR if that's helpful and you can give me some direction on how this problem would best be tackled.

**Comment by marcelveldt** [comment]
It's actually something I'm working on today... It's already improved a lot.
What I can also do is add an option in the addon settings if the artwork should be retrieved for the widgets altough it should get faster once it's in the cache.

I just checked in my changes so far on Git.
Would it be possible for you to give the latest Git version a testdrive to see if it's any faster ?

**Comment by ghost** [comment]
A world of difference with the latest git - default widgets now take 20 seconds to load. None of them now show images in the select dialog, though I can definitely live with that for such a speed improvement! (Especially as the icon for each one is appropriate to its content type)

**Comment by marcelveldt** [comment]
Yes, I removed the images because that was the speed killer. Instead I've set some default skin thumbs.
Is it 20 seconds all the time or is it also faster for subsequent launches ?

**Comment by ghost** [comment]
Second launch without restarting Kodi - 7 seconds.

After restarting Kodi - 24 seconds this time (though I didn't wait for all the various startup scripts to settle down first. The only two that take any significant time - 6 and 14 seconds - are `service.library.data.provider - Recent Videos` and `script.skin.helper.service - Recommended Media`.

**Comment by marcelveldt** [comment]
OK, thanks I will look into those

**Comment by marcelveldt** [comment]
OK, another attempt. Can you grab the latest from git again ?

**Comment by ghost** [comment]
First run after loading Kodi - 3 seconds.
Subsequent run without reloading Kodi - 2 seconds.

Superb work.

**Comment by marcelveldt** [comment]
great :-)

**Comment by ghost** [comment]
Thanks for your time on this, and the quick fix.

**Comment by marcelveldt** [comment]
you're welcome, thanks for testing!
