### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Nessus85100** [marcelveldt/script.skin.helper.service#47]
Hi Marcel
I like to ask you if it's possible to add some new features in your script and i think is better to post them here instead of among the thousands posts in script's forum.
1. The first one is this... https://github.com/marcelveldt/script.skin.helper.service/issues/18.
   I am just putting it here as... bump
2. The second one is if you can add the function from Phil's [script.libraryeditor](https://github.com/phil65/script.libraryeditor).
   If you remember we've talked about this in the forums and you told you need a permission from Phil.
   So @phil65... is this ok for you ?
3. The third it's another function from Phil's scripts and it's the ability to navigate a list by jumping to a title by the first letter. It's the same thing that the shift+[letter] does. Phil has [some code ready](https://github.com/phil65/script.toolbox/blob/master/resources/lib/Utils.py#L272) about this in script.toolbox but when i ask him last year he said that some core code is needed for this work so it was not possible then. So, is it possible to do this now ?. Of course again if it's ok with @phil65.
4. And the last one is if you can also add the ability to open Kodi's select dialog like you do for the Ok, Yes/No and Textviewer dialogs. Again Phil's [script.toolbox does this](https://github.com/phil65/script.toolbox/blob/master/resources/lib/Utils.py#L304) but its limited to 20 items. IMHO this should be unlimited or at least 100 items.

Since most of these are functions from Phil's scripts you might wonder why not post them in appropriate scripts.The main reason is that both those scripts (script.libraryeditor and script.toolbox) they are not in the official repo and i dont think they will be in any time soon. If @phil65 thinks i am wrong about this then i can post them in his appropriate scripts.

Thank you in advance
Nessus

**Comment by phil65** [comment]
script.toolbox is on the repo... (not really mainained anymore though since I got sick of all those workaround-ish hacks)
For the rest... feel free to take all you want, i didnt put a GPL license on it just for fun. ;)

**Comment by phil65** [comment]
One small advice though... if you think about adding more features to this script, please consider splitting your stuff up into smaller scripts. This helper add-on has become quite some monster and should get split into as much pieces as possible. (ideally not more than one extension point for every add-on)

**Comment by marcelveldt** [comment]
Hey Phil, thanks for the feedback. You're right it has become pretty large over time.
I get your point of splitting stuff up into seperate addons but the main idea behind this addon was to have 1 addon for all skin related stuff. Features can be enabled by the skinner by setting skin Bools.

Besides that, a lot of code is shared so if I want to split it up, I'd be duplicating code into seperate addons which is something I don't like personally.Any ideas about that ?

As for the requests by Nessus, it feels a bit strange to copy over existing stuff but if you say it's okay with you I can give it a shot.Or I can submit a PR to you to extend script.toolbox

**Comment by phil65** [comment]
> I get your point of splitting stuff up into seperate addons but the main idea behind this addon was to have 1 addon for all skin related stuff. Features can be enabled by the skinner by setting skin Bools.

I went that route once, too. (putting everything into extendedinfo) 
Took me 2 years to realize that this way is crap. Perhaps you can realize that a bit earlier than me. ;)
It might be convenient for a skinner to just include a single script, but in terms of long-term maintainability and speed (think about low-powered platforms..)  etc this is way worse. Stuff like a color picker (with its own XMLs etc) definitely should be a separate add-on if you ask me.

> Besides that, a lot of code is shared so if I want to split it up, I'd be duplicating code into seperate addons which is something I don't like personally.Any ideas about that ?

Quite easy answer: create a module lib (script.module.xxx) and import shared code into all your other add-ons. That will also lead to nicer more modular code automatically.

**Comment by marcelveldt** [comment]
> It might be convenient for a skinner to just include a single script, but in terms of long-term maintainability and speed (think about low-powered platforms..) etc this is way worse. Stuff like a color picker (with its own XMLs etc) definitely should be a separate add-on if you ask me.

I can certainly look into breaking it up in parts, I especially like the idea of creating resource modules, I will read into that. Only challenge will be backwards compatability but that might even fixable by including the resource modules in the toplevel skinhelper script. So skinners can decide to only use a part of the functionality and use one of the partial addons directly while they'll be able to use all stuff by including the skin helper service...

Thanks for the tips !

**Comment by phil65** [comment]
Sure, breaking changes should only be made for the actual development version (krypton in this case)
If you want some examples, I already created 4 helper modules based on code taken from my main script.
https://github.com/phil65/script.module.kodi65
https://github.com/phil65/script.module.actionhandler
https://github.com/phil65/script.module.t9.search
https://github.com/phil65/script.module.autocompletion

That way not only my main project code stays managable, but that module code can also get  re-used by other projects and it also helps to keep a sane architecture for the main scripts.

As said, this is just a suggestion, were  also fine of course if you just continue with your current way. I just want to avoid that you will take the same path as me ;) (--> realizing too late that all-in-one solutions do more harm than good, and then spend 80% of time on refactoring to clean up all the mess)

**Comment by marcelveldt** [comment]
@Nessus85100 

Would it be possible for you to make a seperate issue for each request, that way it will be easier for me to track the requests.

About your requests:

1) I will start working on this next week. It is now requested more than once and it seems that the nextaired addon is not maintained very actively.

2) Uhm, can you explain why I should copy the same features to the skinhelper script ? Maybe it's a better choice if I just PR the required changes to phil for the already existing script ? Or am I missing something here ?

3) This is just added, the skip to list thing. I have created an seperate issue for that already.

4) As for your request number 4, the select dialog. This is already in the script in a very advanced way.
Take a look at the documentation for the skin settings. Also, you might want to take a look at my Titan skin as a reference because it uses pretty much all stuff in the script.

README for the select/skin settings stuff:
https://github.com/marcelveldt/script.skin.helper.service#set-skin-setting

**Comment by Nessus85100** [comment]
@marcelveldt 
1. Thanks. There is already a separate (old) issue about this https://github.com/marcelveldt/script.skin.helper.service/issues/18.
2. That addon it's not in the official repo and since it's not maintained any more and as Phil said above he has no problem to copy the functions, i think it's worth to add it. It's very useful feature. Personally i use it all the time.
3. Thanks, will test it and let you know in issue's comments
4. Well, i know about the skinsettings.xml file feature. I just don't want to use this since i don't need any other functions from there. I can use Phil's script.toolbox function but it has a limit of 20 items. If you cant add this i can create an issue in Phil's script.toolbox. No problem.

EDIT: Just realize that the only one that needs a separate issue is No2. Do you want me to create a new issue only for this ?

Thanks
Nessus
