### ISSUE TITLE
feature request: ratings from multuiple sources

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#5]
by default the chosen scrapers will only return ratings for one source.
it would be nice to interface directly with the various scrappers' to get ratings.

universal scrapper seems to already have support via several support/info addons for this you just need to use python to interface with them because the scraper only supports one selection of a source.

the "dream" is to have the ability to display in the skin ratings for a movie or tv show from at least these sources:

imdb, rotten tomatoes, trakt and metacritic 

maybe also tvdb, tmdb, etc as well

Thanks for your consideration of this FR,.

Mario

PS - if you do add support, I would love to add this as a feature in Titan :)

**Comment by marcelveldt** [comment]
Guess this request can be dropped because this going to be added to Kodi natively

**Comment by mgonzales71** [comment]
That's cool - hadn't read the roadmap for K\* yet - actually since rotten tomatoes was added to your helper script I can now see both that and ratings from IMDB (on movies) so that was very helpful - thanks 

Maybe you could extend to tv shows also.. They are rated at RT in addition to movies.

Else I'll just wait for the native feature support :)

Thank you

**Comment by marcelveldt** [comment]
I'll close this one for now. Multiple ratings has been added to Kodi core.
Also RT ratings for shows is added to the script a while back.
