### ISSUE TITLE
SkinHelper.EnableAddonsLookups:  use local library artwork first then lookup online

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#58]
suggestion that when enabled/used that artwork be used if found locally in the library before online lookup is used.

this will allow continuity for show and movie artwork for instance if I prefer a banner, clearlogo, etc other then the first default found online it will be used first.

if this doesnt make sense let me know and I can explain better.

thanks a million as always Marcel!

Mario

**Comment by marcelveldt** [comment]
done in current version.

**Comment by mgonzales71** [comment]
Hi Marcel,

Noticed a quirk where this doesn't seem to work.

Have a TV Show - Midnight, Texas
Created and added clearart.png to TV Show Folder then in skin added this local artwork to the tv show library item

trying to use the artwork with the following 

http://localhost:52307/getartwork&amp;title=$INFO[Window(Home).Property(SkinHelper.Player.Title)]&amp;type=clearart

in a texture control fails with the following error:

22:27:52.261 T:1600   DEBUG: Curl::Debug - TEXT: timeout on name lookup is not supported
22:27:52.261 T:1600   DEBUG: Curl::Debug - TEXT: Hostname localhost was found in DNS cache
22:27:52.261 T:1600   DEBUG: Curl::Debug - TEXT:   Trying 127.0.0.1...
22:27:52.262 T:1600   DEBUG: Curl::Debug - TEXT: Connected to localhost (127.0.0.1) port 52307 (#2)
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: HEAD /getartwork&title=Midnight, Texas&type=clearart HTTP/1.1
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: Host: localhost:52307
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: User-Agent: Kodi/17.5-RC1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.5-RC1-Git:20170902-94bf83f
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: Accept: */*
22:27:52.263 T:1600   DEBUG: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
22:27:52.266 T:11032   DEBUG: Skin Helper Service --> webservice.getartwork called with args: {'type': u'clearart', 'title': u'Midnight, Texas'}
22:27:52.274 T:1600   DEBUG: Curl::Debug - TEXT: The requested URL returned error: 404 Not Found
22:27:52.274 T:1600   DEBUG: Curl::Debug - TEXT: Closing connection 2
22:27:52.274 T:1600   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url http://localhost:52307/getartwork&title=Midnight, Texas&type=clearart

yet - if I use that in a texture control where the artwork exists online - it works just fine.

doesn't seem to be checking for local artwork from what I can tell.
