### ISSUE TITLE
icon and fanart

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#6]
something I drafted for you - can adjust etc per your request

![skin helper service icon 1](https://cloud.githubusercontent.com/assets/6510026/9561212/239853e8-4df1-11e5-9b1e-a47c3db16e82.png)
![skin helper service icon 5](https://cloud.githubusercontent.com/assets/6510026/9561327/616f5d02-4df5-11e5-977e-a81f602aae56.png)

some more drafts

![shs alt icon 1](https://cloud.githubusercontent.com/assets/6510026/9580489/b00d9996-4fae-11e5-8c0b-a2affee7b8d7.png)
![shs alt icon 2](https://cloud.githubusercontent.com/assets/6510026/9580490/b00f57fe-4fae-11e5-9154-d26163c89099.png)
![shs alt icon 3](https://cloud.githubusercontent.com/assets/6510026/9581088/2b6bc420-4fb2-11e5-8ead-fbd4556e3114.png)
![shs alt icon 4](https://cloud.githubusercontent.com/assets/6510026/9581446/6b6905cc-4fb4-11e5-8756-36cbdad925cc.png)

![shs alt icon 6](https://cloud.githubusercontent.com/assets/6510026/9623491/58160cc0-50f6-11e5-8556-3fd5f9b7fcbf.png)
![shs alt icon 7](https://cloud.githubusercontent.com/assets/6510026/9623493/5816c0b6-50f6-11e5-8c1a-ac3a0b65124c.png)
![shs alt icon 8](https://cloud.githubusercontent.com/assets/6510026/9623494/58177c5e-50f6-11e5-8402-3dd7062a40bb.png)
![shs alt icon 9](https://cloud.githubusercontent.com/assets/6510026/9623492/581683c6-50f6-11e5-8ed4-3b9d99ac7d69.png)

**Comment by mgonzales71** [comment]
fanart 
![skin helper service fanart 2](https://cloud.githubusercontent.com/assets/6510026/9561219/40dd1cf4-4df1-11e5-9cab-a4baa782f328.png)
![skin helper service fanart](https://cloud.githubusercontent.com/assets/6510026/9561220/40de62c6-4df1-11e5-8a96-64a80e51639b.png)
![skin helper service fanart 3](https://cloud.githubusercontent.com/assets/6510026/9561228/a43879ec-4df1-11e5-847b-da023174ded7.png)

**Comment by mgonzales71** [comment]
my favorites are 2nd icon and 3rd fanart

**Comment by mgonzales71** [comment]
another crop of icons...

first one has a slightly opaque background followed by variations of backgrounds, a few with added drop shadow as well

![shs alt icon 16](https://cloud.githubusercontent.com/assets/6510026/9696967/ab3d0aac-5330-11e5-943d-aefad2089304.png)
![shs alt icon 10](https://cloud.githubusercontent.com/assets/6510026/9696964/ab28bdb8-5330-11e5-8454-45c0eedade86.png)
![shs alt icon 11](https://cloud.githubusercontent.com/assets/6510026/9696966/ab2a7b62-5330-11e5-8d77-578eabc6eab7.png)
![shs alt icon 12](https://cloud.githubusercontent.com/assets/6510026/9696962/ab27ec44-5330-11e5-923a-450a9e138935.png)
![shs alt icon 13](https://cloud.githubusercontent.com/assets/6510026/9696961/ab27dd26-5330-11e5-95e6-e37b8d6ad744.png)
![shs alt icon 14](https://cloud.githubusercontent.com/assets/6510026/9696963/ab288384-5330-11e5-86dc-8acbc57c75d5.png)
![shs alt icon 15](https://cloud.githubusercontent.com/assets/6510026/9696965/ab2991c0-5330-11e5-9cb0-e7fee406c4cb.png)

**Comment by mgonzales71** [comment]
and finally 2 fanart variations with and without drop shadow using white artwork on blue background
:smile:

![skin helper service fanart 4](https://cloud.githubusercontent.com/assets/6510026/9698523/05dd04d8-536f-11e5-959d-18e5aeaba4f4.jpg)
![skin helper service fanart 3](https://cloud.githubusercontent.com/assets/6510026/9698524/08c8ed9c-536f-11e5-8356-0d74e093a695.jpg)

**Comment by marcelveldt** [comment]
Thanks Mario for creating this!
I have included your icon and fanart in the script.

That was the last thing I needed before I could push the first version to the Kodi repo.

**Comment by mgonzales71** [comment]
You're welcome - if you want me to change anything, let me know.  Glad to help where and when I can :smile:
