### ISSUE TITLE
PVR Artwork from EPG

### ISSUE THREAD

**Issue by lightglitch** [marcelveldt/script.skin.helper.service#62]
Add lockup for artwork for PVR from EPG instead of just the recordings.

**Comment by marcelveldt** [comment]
what do you mean with this exactly ?

Do you mean the random PVR background ? In that case, you can enable that in the settings

**Comment by walterheisenberg** [comment]
@lightglitch 
You can use skinhelpers http-request for this. I have modded SiLVOs AeonNox to do this:
http://forum.kodi.tv/showthread.php?tid=291830

@marcelveldt 
I have errors in the log using the mentioned functions everytime no images are found:
http://pastebin.com/Szk5N28f
here is the used function:
http://localhost:52307/getpvrthumb&amp;title=$INFO[VideoPlayer.Title]&amp;type=clearart,banner,poster

It does also give errors, and doesn't matter if "&amp;channel=$INFO[VideoPlayer.ChannelName]" is added, so I removed it.

please excuse me for posting this here. If you want, I can open a new issue
Thx

**Comment by marcelveldt** [comment]
Be aware that you need to to use &amp; instead of &
