### ISSUE TITLE
widgetType not returned for audio service.library.data.provider widgets

### ISSUE THREAD

**Issue by ghost** [marcelveldt/script.skin.helper.service#7]
As title, the widgetType property doesn't appear to be being set for the library data provider audio widgets - both the album widgets and the song widget. TV and movie confirmed as returning correct widgetType, sorry haven't had time to test music videos yet :)

Cheers.

**Comment by marcelveldt** [comment]
Thanks for testing! Will fix it tonight

**Comment by marcelveldt** [comment]
This is now fixed on Git. I will also do a PR for the same improvement in the skinshortcuts code.

**Comment by ghost** [comment]
Thanks :)
