### ISSUE TITLE
[PVR channel widget] EPG info isn't refreshed.

### ISSUE THREAD

**Issue by mac1202** [marcelveldt/script.skin.helper.service#71]
Hi, with the new version of skin helper service, the EPG info displayed in the PVR channel widget doesnt refresh properly. It use the EPG info of the first time you set up the widget, after that the widget never refresh it.

**Comment by marcelveldt** [comment]
What skin are you using ?
Or did you setup the path yourself ?

In any case, you must make sure that you also have the reload parameter attached to the path, otherwise the widget will never refresh.

Example code:

> plugin://script.skin.helper.widgets/?action=recordings&amp;mediatype=pvr&amp;reload=$INFO[Window(Home).Property(widgetreload2)]

**Comment by mac1202** [comment]
I use Mimic git with kodi 17 git. I used the preconfigured widget in mimic. Path seems to be correctly setup.
[Screenshot](http://i.imgur.com/aY1Opyb.png)

**Comment by marcelveldt** [comment]
Is the issue resolved in the latest new beta versions ?

**Comment by mac1202** [comment]
I m currently with version 1.0.141, it's better than when I first reported the issue, but can't say it's work properly. For example have started kodi since 10 minutes and the info on the widget doesnt have been refreshed yet. I will test again when 1.0.142 hit your beta repo.

**Comment by mac1202** [comment]
Just tested the current git version issue still present.

**Comment by mac1202** [comment]
I think it s a more global problem with widget refreshing. For example in older version of skin widget when i was playing a episode from the next episode widget, when the episode ended and i was bringing back to the home screen, the widget was immediatly refreshed to display me a new episode of this tvshow. Now with the current version it isnt refreshed.

**Comment by marcelveldt** [comment]
this should now be fixed in current beta versions. Please install from my beta repo

**Comment by mac1202** [comment]
it seems to be fixed, thank for your time. I closed it.
