### ISSUE TITLE
skin control focus while script populates properties (info dialog)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#74]
FYI - this one is odd...

but I noticed tonight (so could be issue with latest commit(s) or not) that if I press I for Info (using krypton nightly with keyboard controls) the control focus is lost and moving around will keep loosing control focus (like a tug of war) until the properties are populated for the dialog by the script(s).  was using latest titan skin beta for K*.

**Comment by marcelveldt** [comment]
this should be fixed.
