### ISSUE TITLE
Add "videos" as content type

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.skin.helper.service#75]
Hi,

Would it be possible to add "videos" as a content type similar to "movies" when getting content types?

If you would be willing, I guess this means adding it to:
**script.skin.helper.service/resources/lib/utils.py
get_current_content_type()**
and changing this line:
**elif xbmc.getCondVisibility("Container.Content(movies) + !substring(Container.FolderPath,setid=)"):
            content_type = "movies"**

to something like:
**elif xbmc.getCondVisibility("[Container.Content(movies) | Container.Content(videos)] + !substring(Container.FolderPath,setid=)"):
            content_type = "movies"**
My problem is that the **Kodi Youtube add-in** has Container.Content=videos, and therefore the list of available views is 3 (panel list, thumbs, list) instead of the 15 or so offered by my skin. I use skin **Eminence 2 MOD** for Krypton, but I guess this change would benefit any skin.

As a test, I put the value of Container.Content in a label in the top left corner:
![screenhunter_78 jan 04 14 52](https://cloud.githubusercontent.com/assets/18152888/21644363/6de3294c-d28d-11e6-8e19-11b09d1f450a.jpg)

**Comment by hablaras** [comment]
Hmm, just changing lines in the /extra/views.xml also solves my issue, so this issue can be closed.

e.g I can just change
    &lt;view id="Posters" value="52" languageid="31651" type="movies,tvshows"/&gt;
into:
    &lt;view id="Posters" value="52" languageid="31651" type="movies,videos,tvshows"/&gt;
without any change needed to script.skin.helper.service.

**Comment by marcelveldt** [comment]
changing it globally is not an option, that will cause many issues.
Your current solutionb by fixing it in the views.xml is the proper one.

I will also add videos as an additional content type...
