### ISSUE TITLE
Message Dialog (textviewer) issue?

### ISSUE THREAD

**Issue by Nessus85100** [marcelveldt/script.skin.helper.service#79]
I am using the following to show what's new in AddonInfo...
`RunScript(script.skin.helper.service,action=textviewer,header=[yourheadertext],message=[your message body])`

The problem is that this is not working if i am not using some quotes in message attribute.

This is working properly...
`<onclick>RunScript(script.skin.helper.service,action=textviewer,header=$LOCALIZE[24054],message='"$INFO[ListItem.AddonNews])"'</onclick>`

...and this is not. it shows only the first line...
`<onclick>RunScript(script.skin.helper.service,action=textviewer,header=$LOCALIZE[24054],message=$INFO[ListItem.AddonNews])</onclick>`

The thing is that those quotes ("') are visible in textviewer in the begging of the text and is not looking good.

Is there any fix on this or am i doing something in the code?

Thanks
Nessus

**Comment by Nessus85100** [comment]
Weird!... without the quotes in some addons it works properly and in some it's not!

I've checked the skins in Krypton Kodi addon repo.
Aeon Nox it's not working and Mimic is working fine.
I think it depends on the size of text that is displayed so i guess this is a bug ?

**Comment by sualfred** [comment]
It's a escaping issue of Kodi. Use this instead:
			<onclick>RunScript(script.skin.helper.service,action=textviewer,header='$ESCINFO[ListItem.Label]',message='$ESCINFO[ListItem.AddonNews]')</onclick>

The '' and $ESCINFO/$ESCVAR are important.

**Comment by Nessus85100** [comment]
Well, with the '' and $ESCINFO/$ESCVAR it works properly but still the quotes are showing in textviewer.
Is this how it suppose to work ?... because if it is, is very annoying! @marcelveldt ?

**Comment by sualfred** [comment]
The problem does not exist if you use Phil's toolbox.

@marcelveldt 
Maybe you should check his implementation

**Comment by marcelveldt** [comment]
OK, will do. Sorry for the late reply. Hard for me to follow both the forums and github for issues

**Comment by Nessus85100** [comment]
@marcelveldt 
I've fix this by editing the code in main_module.py

It just needs to replace this code:
```
if bodytxt.startswith(" "):
  bodytxt = bodytxt[1:]
if headertxt.startswith(" "):
```
... with this one:
```
if bodytxt.startswith("'"):
    bodytxt = bodytxt[1:-1]
if bodytxt.startswith('"'):
    bodytxt = bodytxt[1:-1]
if headertxt.startswith(" "):
```
I have no idea if this is the proper way to do it but it works fine. You know better.
Sorry but i am not so familiar with the pull requests stuff so to make one for this.

Cheers
Nessus

**Comment by marcelveldt** [comment]
thanks for finding the solution. I will update the code with your proposed changes

**Comment by Nessus85100** [comment]
@marcelveldt 
You've added this for the YesNo & Ok dialogs.
It was needed for the Textviewer dialog (it's on the title of the issue).

PS. Dunno if its also needed for YesNo & Ok dialogs

**Comment by Nessus85100** [comment]
@marcelveldt 
Can i gently bump on this!
I am planning to submit my skin to official repo and wanted all to work properly.

Thanks
Nessus

**Comment by marcelveldt** [comment]
Sorry for the late reponses... Been busy with family stuff lately and work.

I am catching up with some requests and bugfixes this week and after that I will submit an update to the repo.

**Comment by Nessus85100** [comment]
@marcelveldt 
bump?

I have commented this here... https://github.com/marcelveldt/script.skin.helper.service/commit/7673e20a3a8bd153025d445213f8e6db811be453#diff-6cd6906a88953a03489b1002f6ecb34dR617

**Comment by marcelveldt** [comment]
Finally had the chance to fix this. I submitted the new code just now on Git. Can you test it with some scenarios please ?

**Comment by Nessus85100** [comment]
Working fine now in all places.
Thanks

**Comment by marcelveldt** [comment]
OK, great! Thanks for testing. I will submit updates to the Kodi repo at the end of this week.
