### ISSUE TITLE
Empty Widget list - variable 'mediaLibrary' referenced before assignment

### ISSUE THREAD

**Issue by nullket** [marcelveldt/script.skin.helper.service#80]
Hello,
I am using the Estuary MOD Skin and choosing a widget with "Skin Helper Service Widgets" returns an empty list. The log says that some variable "mediaLibrary"  is referenced before assignment. I atteched the Kodi log in debug-mode:
http://pastebin.com/dB9cUDi9

**Comment by marcelveldt** [comment]
You are using an outdated version, please make sure that you update to the latest version. Most likely it will be provided on the skinner's repo or else you can install my repo.

**Comment by marcelveldt** [comment]
Also,

**Comment by nullket** [comment]
That was very quick, thank you very much!
Sorry for the inconvenience.
