### ISSUE TITLE
Latest Update 1.1.1

### ISSUE THREAD

**Issue by jaaxx** [marcelveldt/script.skin.helper.service#81]
Using Mimic skin on Krypton final, getting the following error constantly - 

> if dbid and (not transaction or bgtasks < 2):
                                            NameError: global name 'bgtasks' is not defined

I noticed a recent commit (a31a324) to kodi_monitor.py adding some bgtasks code. Log says it's triggered once on line 51 and once on line 102 per event.

**Comment by marcelveldt** [comment]
small typo, thanks for the catch. Will fix it tonight
