### ISSUE TITLE
Favorites widget not working

### ISSUE THREAD

**Issue by huyz11** [marcelveldt/script.skin.helper.service#83]
I noticed on krypton, using the Aeon Nox 5: SiLVO skin, that the items in the Favorites widget will not open. Well the kodi addons in the favorite widget will not open however android apps i added to the favorites widget do open.
Downgrading Skin Helper Service to version 1.0.100 fixes the issue. Fails on version 1.1.3

**Comment by huyz11** [comment]
Also fails on version 1.1.9

**Comment by marcelveldt** [comment]
it should be fixed in latest version. BTW, it's the skin helper widgets addon. you're talking about.

**Comment by huyz11** [comment]
This issue seems to be happening on Bubbles Aeon Nox 5 also.
