### ISSUE TITLE
Movie sets Art properties are empty

### ISSUE THREAD

**Issue by Nessus85100** [marcelveldt/script.skin.helper.service#86]
All the SkinHelper.ListItem.X.Art.foo properties are returning empty

I use this for the cd art...
`$INFO[Window(Home).Property(SkinHelper.ListItem.x.Discart)`
and i get nothing.

Am i doing something wrong or it's a bug?

Cheers
Nessus

**Comment by marcelveldt** [comment]
Are you testing this with repo version or current beta/github version ?

**Comment by Nessus85100** [comment]
I have your repo installed so i am on 1.1.10 which is the same with github.

**Comment by Nessus85100** [comment]
@marcelveldt 
Can i gently bump on this!
I am planning to submit my skin to official repo and wanted all to work properly.

Thanks
Nessus

**Comment by Nessus85100** [comment]
@marcelveldt 
bump?

**Comment by marcelveldt** [comment]
Oops, this is actually a typo in the wiki...

$INFO[Window(Home).Property(SkinHelper.ListItem.0.Art.Discart)]

**Comment by marcelveldt** [comment]
Hmmm, or not. It's correct in the wiki but wrong in your code snippet...

Anyways, I've just tested it on my setup and it's working fine. Tried several properties and all returned info

**Comment by Nessus85100** [comment]
It's working fine now with the code from wiki.
I could swear that was not when i try it before i open this issue!

Anyway, the important thing is that is working.

Thanks

**Comment by marcelveldt** [comment]
ok, great to hear that it is indeed working fine.
