### ISSUE TITLE
Window(Home).Property(SkinHelper.ListItem.Rating) returns a lot of decimals for PVR recordings

### ISSUE THREAD

**Issue by gade01** [marcelveldt/script.skin.helper.service#92]
Hi Marcel.

As reported here: https://forum.kodi.tv/showthread.php?tid=316260 ,
Window(Home).Property(SkinHelper.ListItem.Rating) can return a lot of decimals for PVR recordings.

Note that I haven't experienced this though, but I have an extremely limited PVR setup.

Maybe it's possible to reduce the decimals to 1, maybe 2?

**Comment by marcelveldt** [comment]
Are you sure this is SkinHelper.ListItem.Rating ?
Not SkinHelper.ListItem.Rating.tvdb or SkinHelper.ListItem.Rating.tmdb ?

**Comment by gade01** [comment]
I only use Window(Home).Property(SkinHelper.ListItem.Rating) in Rapier.

As I wrote, I didn't experience this at all. But I don't use PVR very much. Only the demo add-on and nextpvr for tv and iptvsimple for radio.

**Comment by gade01** [comment]
Karellen, who reported it at the forums, uses NextPVR as well (although it probably doesn't make a difference).

<img src="https://image.ibb.co/hK3rdF/IMG_1368.jpg" width="600">

**Comment by marcelveldt** [comment]
Hmm, I can't reproduce the issue. Somehow it looks like the rating is retrieved from NextPVR or something. Anyways, I'll add in a quick fix which will force any float to just 1 decimal when setting the window properties, that should fix it. Will be available in the next release of skin helper.

**Comment by gade01** [comment]
Sounds absolutely perfect, thanks a lot.
