### ISSUE TITLE
Favorites widget not working again

### ISSUE THREAD

**Issue by huyz11** [marcelveldt/script.skin.helper.service#97]
Items favorites widget on Bubble Aeon Nox fail to launch. This is a similar issue to an old issue i posted from but different skin:
https://github.com/marcelveldt/script.skin.helper.service/issues/83

Sorry couldn't find a section to post issues on for skin helper widget

**Comment by marcelveldt** [comment]
favorites widget is working fine on my end. Which version are you running of the skin helper widgets add-on ?

**Comment by huyz11** [comment]
Running verion 1.1.22 of skin helper widget. Only android apps added to the favorites widget seem to be launch-able.

**Comment by Angelinas1** [comment]
try new version, if you have same isue please open new isue
