### ISSUE TITLE
possibly useful artwork resource: squaredtvart

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#98]
Could be useful added feature for the addon (or modules) at some point.

especially in "square" or icon (even list with icon) views?

http://squaredtvart.tumblr.com/

![](http://68.media.tumblr.com/1ba7ddd173e730c120b647a77e3832e2/tumblr_nmo5moZVYl1r8iw09o1_1280.jpg)

**Comment by Angelinas1** [comment]
Skin can make simular image... tnx
