### ISSUE TITLE
local artwork (revisit)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#99]
Hi Marcel,

wanted to ask about a previous issue if you get a moment.

https://github.com/marcelveldt/script.skin.helper.service/issues/58

Noticed a quirk where this doesn't seem to work.

Have a TV Show - Midnight, Texas

Created and added clearart.png to TV Show Folder then in skin added this local artwork to the tv show library item

then tried to lookup and use the artwork with the following (there is no online clearart it seems)

http://localhost:52307/getartwork&amp;title=$INFO[Window(Home).Property(SkinHelper.Player.Title)]&amp;type=clearart

in a texture control this fails with the following error:

```
22:27:52.261 T:1600   DEBUG: Curl::Debug - TEXT: timeout on name lookup is not supported
22:27:52.261 T:1600   DEBUG: Curl::Debug - TEXT: Hostname localhost was found in DNS cache
22:27:52.261 T:1600   DEBUG: Curl::Debug - TEXT:   Trying 127.0.0.1...
22:27:52.262 T:1600   DEBUG: Curl::Debug - TEXT: Connected to localhost (127.0.0.1) port 52307 (#2)
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: HEAD /getartwork&title=Midnight, Texas&type=clearart HTTP/1.1
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: Host: localhost:52307
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: User-Agent: Kodi/17.5-RC1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.5-RC1-Git:20170902-94bf83f
22:27:52.262 T:1600   DEBUG: Curl::Debug - HEADER_OUT: Accept: */*
22:27:52.263 T:1600   DEBUG: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
22:27:52.266 T:11032   DEBUG: Skin Helper Service --> webservice.getartwork called with args: {'type': u'clearart', 'title': u'Midnight, Texas'}
22:27:52.274 T:1600   DEBUG: Curl::Debug - TEXT: The requested URL returned error: 404 Not Found
22:27:52.274 T:1600   DEBUG: Curl::Debug - TEXT: Closing connection 2
22:27:52.274 T:1600   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url http://localhost:52307/getartwork&title=Midnight, Texas&type=clearart

```
yet - if I use that in a texture control where the artwork exists online for a tv show or movie - it works just fine.

doesn't seem to be checking for local artwork from what I can tell.

Thanks,

Mario

**Comment by marcelveldt** [comment]
Mario, can you check with $ESCINFO instead of $INFO ?

**Comment by mgonzales71** [comment]
Some more background....

I am working on better with Titan skin (krypton) and getting better clearart support for TV Shows and Movies.

Working with the following code in the IncludesVariables.xml

```
   <variable name="VideoPlayerClearArt">
	<value condition="!String.IsEmpty(Player.Art(tvshow.clearart))">$INFO[Player.Art(tvshow.clearart)]</value>
	<value condition="!String.IsEmpty(Player.Art(clearart))">$INFO[Player.Art(clearart)]</value>
	<value condition="!String.IsEmpty(Player.Art(clearlogo))">$INFO[Player.Art(clearlogo)]</value>
	<value condition="!String.IsEmpty(Player.Art(tvshow.clearlogo))">$INFO[Player.Art(tvshow.clearlogo)]</value>
    <value condition="!String.IsEmpty(Window(Home).Property(SkinHelper.Player.Art.ClearArt))">$INFO[Window(Home).Property(SkinHelper.Player.Art.ClearArt)]</value>
	<value condition="!String.IsEmpty(Window(Home).Property(SkinHelper.Player.Art.ClearLogo))">$INFO[Window(Home).Property(SkinHelper.Player.Art.ClearLogo)]</value>
	<value>http://localhost:52307/getartwork&amp;title=$ESCINFO[Window(Home).Property(SkinHelper.Player.Title)]&amp;type=clearart</value>
   </variable>

```

Using $ESCINFO get the following error:


```
18:12:37.142 T:9612   DEBUG: Curl::Debug - TEXT: timeout on name lookup is not supported
18:12:37.142 T:9612   DEBUG: Curl::Debug - TEXT: Hostname localhost was found in DNS cache
18:12:37.143 T:9612   DEBUG: Curl::Debug - TEXT:   Trying 127.0.0.1...
18:12:37.164 T:9612   DEBUG: Curl::Debug - TEXT: Connected to localhost (127.0.0.1) port 52307 (#1)
18:12:37.176 T:9612   DEBUG: Curl::Debug - HEADER_OUT: HEAD /getartwork&title="Midnight, Texas"&type=clearart HTTP/1.1
18:12:37.176 T:9612   DEBUG: Curl::Debug - HEADER_OUT: Host: localhost:52307
18:12:37.176 T:9612   DEBUG: Curl::Debug - HEADER_OUT: User-Agent: Kodi/17.5-RC1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.5-RC1-Git:20170902-94bf83f
18:12:37.176 T:9612   DEBUG: Curl::Debug - HEADER_OUT: Accept: */*
18:12:37.177 T:9612   DEBUG: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
18:12:37.254 T:9612   DEBUG: Curl::Debug - TEXT: The requested URL returned error: 404 Not Found
18:12:37.254 T:9612   DEBUG: Curl::Debug - TEXT: Closing connection 1
18:12:37.254 T:9612   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url http://localhost:52307/getartwork&title="Midnight, Texas"&type=clearart
```

The artwork is assigned to the tv show:

![kodi_2017-09-06_18-19-38](https://user-images.githubusercontent.com/6510026/30141416-2e9aa6f2-9330-11e7-987d-88df064613e3.png)

but as I mentioned - this is local artwork I created (not available online).  If there is artwork online it is found just fine.

Thanks,

Mario

**Comment by mgonzales71** [comment]
I should also mention for instance - a movie I have locally on a NAS server - has all artwork downloaded and available locally in the same folder with all the proper names, etc but still (now this is in Titan Skin mind you) online lookups for all artwork is done.  I only mention this as a side note - because it adds extra work (online lookup, etc) when not needed and delays populating artwork to the skin.

**Comment by mgonzales71** [comment]
Another example to help illustrate how the helper script will favor online artwork over what is already downloaded and available locally - normally I would not care or mind since artwork is displayed and I don't mind variety - except in instances of where no artwork is available online but it is locally and it is not shown

![kodi_2017-09-06_20-51-15](https://user-images.githubusercontent.com/6510026/30145296-54ff126e-9345-11e7-8c19-44b2f83f60fe.png)

![kodi_2017-09-06_20-50-51](https://user-images.githubusercontent.com/6510026/30145365-adacd87e-9345-11e7-9ffc-6bc8d71c16d6.png)

**Comment by marcelveldt** [comment]
Mario, the web service call to get artwork will only do an online lookup, it doesn't even do a local lookup.

Window(Home).Property(SkinHelper.Player.Art.ClearLogo) should get you the clearlogo like it is in the local library. 
There is a warning however, this will only work with library content, so media on your disk/nas and and not streams

I will take a look if I can easily add a quick lookup in the local DB when using the web service.

BTW: Quick note; you must add mediatype=tvshow to the web service call

**Comment by mgonzales71** [comment]
Ok - I may have overlooked that the web service was online only.  I could have sworn I read it referenced simplecache first and thus would use local and artwork previously looked up.  My apologies for missing that distinction.  Thank and as always thanks for your help!

PS - I have had good luck using the above $VAR for both TV and Movies be they local disk, NAS or even a .strm file added to the library.  The only issue I have had was the preference for online artwork over anything local but as you explained that was by design and my bad for missing.

If you do decide to add a check for cached and local artwork before an online lookup please let me know because I would be happy to do some extensive testing and then incorporate the changes with the skins use of OSD artwork during playback.

On average the lookup as-is can be pretty quick but sometimes the responses can be upwards of 8-10 seconds.

Adding a cache and local check can only further improve that response - plus it would help relieve peak loads of the various artwork lookup services 

If I had a future dream for artwork lookup (and meta data) under the skin helper services umbrella it would be to 

Utilizing / creating / modifying nfo files for faster library recovery / backup / migration etc

Add artwork downloading (of missing local artwork if configured) - very basic and quick

Ok - I am rambling now hehe - very much appreciate all your hard work sir!

Thanks again :)

Mario

**Comment by marcelveldt** [comment]
I've added some code today so it will do  quick lookup in local db

**Comment by marcelveldt** [comment]
the delayed responses of 8-10 seconds is because of the rate limiting I implemented to relax the calls to external api's. You can enter your own personal api keys to get rid of that

**Comment by mgonzales71** [comment]
**_opened a more specific issue for the following additional replies that may have been missed.
https://github.com/marcelveldt/script.skin.helper.service/issues/110
[so this can be closed now, or both can be closed - mostly a note to avoid confusion and help tidy up issues once resolved]_**


I have time to get back to this and I am not sure what changed but now the web service seems broken?

for example:
http://localhost:52307/getartwork&title="cops"&type=clearart

returns in browser:
```
404 Not Found

No image found matching the criteria

Traceback (most recent call last):
  File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.cherrypy\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.cherrypy\lib\cherrypy\lib\encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.cherrypy\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\webservice.py", line 54, in getartwork
    return self.handle_artwork(artwork, kwargs)
  File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\webservice.py", line 156, in handle_artwork
    return self.handle_image(image)
  File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\webservice.py", line 178, in handle_image
    raise cherrypy.HTTPError(404, "No image found matching the criteria")
HTTPError: (404, 'No image found matching the criteria')

Powered by CherryPy unknown 
```
worth noting that this lookup still returns something at least:

http://localhost:52307/getthumb&title="cops"

**Comment by mgonzales71** [comment]
i am banging my head against this one - lol 

I know you are busy but if you get a chance let me know if lookups using the web service are still working for you.

figured I ask before I get drastic and revert everything to a clean setup - well actually I may do that tomorrow anyway..

hope all is well!

Mario
